// +build !ignore_autogenerated

/*
Copyright 2020 Weaveworks.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha3 "github.com/weaveworks/cluster-api-provider-existinginfra/apis/cluster.weave.works/v1alpha3"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1alpha3.APIServer)(nil), (*APIServer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_APIServer_To_v1alpha1_APIServer(a.(*v1alpha3.APIServer), b.(*APIServer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Addon)(nil), (*v1alpha3.Addon)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Addon_To_v1alpha3_Addon(a.(*Addon), b.(*v1alpha3.Addon), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.Addon)(nil), (*Addon)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_Addon_To_v1alpha1_Addon(a.(*v1alpha3.Addon), b.(*Addon), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AuthenticationWebhook)(nil), (*v1alpha3.AuthenticationWebhook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthenticationWebhook_To_v1alpha3_AuthenticationWebhook(a.(*AuthenticationWebhook), b.(*v1alpha3.AuthenticationWebhook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.AuthenticationWebhook)(nil), (*AuthenticationWebhook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AuthenticationWebhook_To_v1alpha1_AuthenticationWebhook(a.(*v1alpha3.AuthenticationWebhook), b.(*AuthenticationWebhook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AuthorizationWebhook)(nil), (*v1alpha3.AuthorizationWebhook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthorizationWebhook_To_v1alpha3_AuthorizationWebhook(a.(*AuthorizationWebhook), b.(*v1alpha3.AuthorizationWebhook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.AuthorizationWebhook)(nil), (*AuthorizationWebhook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_AuthorizationWebhook_To_v1alpha1_AuthorizationWebhook(a.(*v1alpha3.AuthorizationWebhook), b.(*AuthorizationWebhook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContainerRuntime)(nil), (*v1alpha3.ContainerRuntime)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContainerRuntime_To_v1alpha3_ContainerRuntime(a.(*ContainerRuntime), b.(*v1alpha3.ContainerRuntime), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.ContainerRuntime)(nil), (*ContainerRuntime)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_ContainerRuntime_To_v1alpha1_ContainerRuntime(a.(*v1alpha3.ContainerRuntime), b.(*ContainerRuntime), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EndPoint)(nil), (*v1alpha3.EndPoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EndPoint_To_v1alpha3_EndPoint(a.(*EndPoint), b.(*v1alpha3.EndPoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.EndPoint)(nil), (*EndPoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_EndPoint_To_v1alpha1_EndPoint(a.(*v1alpha3.EndPoint), b.(*EndPoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FileSpec)(nil), (*v1alpha3.FileSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FileSpec_To_v1alpha3_FileSpec(a.(*FileSpec), b.(*v1alpha3.FileSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.FileSpec)(nil), (*FileSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_FileSpec_To_v1alpha1_FileSpec(a.(*v1alpha3.FileSpec), b.(*FileSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OSConfig)(nil), (*v1alpha3.OSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OSConfig_To_v1alpha3_OSConfig(a.(*OSConfig), b.(*v1alpha3.OSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.OSConfig)(nil), (*OSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_OSConfig_To_v1alpha1_OSConfig(a.(*v1alpha3.OSConfig), b.(*OSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServerArgument)(nil), (*v1alpha3.ServerArgument)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServerArgument_To_v1alpha3_ServerArgument(a.(*ServerArgument), b.(*v1alpha3.ServerArgument), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.ServerArgument)(nil), (*ServerArgument)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_ServerArgument_To_v1alpha1_ServerArgument(a.(*v1alpha3.ServerArgument), b.(*ServerArgument), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SourceSpec)(nil), (*v1alpha3.SourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SourceSpec_To_v1alpha3_SourceSpec(a.(*SourceSpec), b.(*v1alpha3.SourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha3.SourceSpec)(nil), (*SourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_SourceSpec_To_v1alpha1_SourceSpec(a.(*v1alpha3.SourceSpec), b.(*SourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*APIServer)(nil), (*v1alpha3.APIServer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_APIServer_To_v1alpha3_APIServer(a.(*APIServer), b.(*v1alpha3.APIServer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ClusterSpec)(nil), (*v1alpha3.ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterSpec_To_v1alpha3_ClusterSpec(a.(*ClusterSpec), b.(*v1alpha3.ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*MachineSpec)(nil), (*v1alpha3.MachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineSpec_To_v1alpha3_MachineSpec(a.(*MachineSpec), b.(*v1alpha3.MachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.ClusterSpec)(nil), (*ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_ClusterSpec_To_v1alpha1_ClusterSpec(a.(*v1alpha3.ClusterSpec), b.(*ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha3.MachineSpec)(nil), (*MachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MachineSpec_To_v1alpha1_MachineSpec(a.(*v1alpha3.MachineSpec), b.(*MachineSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_APIServer_To_v1alpha3_APIServer(in *APIServer, out *v1alpha3.APIServer, s conversion.Scope) error {
	// WARNING: in.ExternalLoadBalancer requires manual conversion: does not exist in peer-type
	out.AdditionalSANs = *(*[]string)(unsafe.Pointer(&in.AdditionalSANs))
	out.ExtraArguments = *(*[]v1alpha3.ServerArgument)(unsafe.Pointer(&in.ExtraArguments))
	return nil
}

func autoConvert_v1alpha3_APIServer_To_v1alpha1_APIServer(in *v1alpha3.APIServer, out *APIServer, s conversion.Scope) error {
	out.AdditionalSANs = *(*[]string)(unsafe.Pointer(&in.AdditionalSANs))
	out.ExtraArguments = *(*[]ServerArgument)(unsafe.Pointer(&in.ExtraArguments))
	return nil
}

// Convert_v1alpha3_APIServer_To_v1alpha1_APIServer is an autogenerated conversion function.
func Convert_v1alpha3_APIServer_To_v1alpha1_APIServer(in *v1alpha3.APIServer, out *APIServer, s conversion.Scope) error {
	return autoConvert_v1alpha3_APIServer_To_v1alpha1_APIServer(in, out, s)
}

func autoConvert_v1alpha1_Addon_To_v1alpha3_Addon(in *Addon, out *v1alpha3.Addon, s conversion.Scope) error {
	out.Name = in.Name
	out.Params = *(*map[string]string)(unsafe.Pointer(&in.Params))
	out.Deps = *(*[]string)(unsafe.Pointer(&in.Deps))
	return nil
}

// Convert_v1alpha1_Addon_To_v1alpha3_Addon is an autogenerated conversion function.
func Convert_v1alpha1_Addon_To_v1alpha3_Addon(in *Addon, out *v1alpha3.Addon, s conversion.Scope) error {
	return autoConvert_v1alpha1_Addon_To_v1alpha3_Addon(in, out, s)
}

func autoConvert_v1alpha3_Addon_To_v1alpha1_Addon(in *v1alpha3.Addon, out *Addon, s conversion.Scope) error {
	out.Name = in.Name
	out.Params = *(*map[string]string)(unsafe.Pointer(&in.Params))
	out.Deps = *(*[]string)(unsafe.Pointer(&in.Deps))
	return nil
}

// Convert_v1alpha3_Addon_To_v1alpha1_Addon is an autogenerated conversion function.
func Convert_v1alpha3_Addon_To_v1alpha1_Addon(in *v1alpha3.Addon, out *Addon, s conversion.Scope) error {
	return autoConvert_v1alpha3_Addon_To_v1alpha1_Addon(in, out, s)
}

func autoConvert_v1alpha1_AuthenticationWebhook_To_v1alpha3_AuthenticationWebhook(in *AuthenticationWebhook, out *v1alpha3.AuthenticationWebhook, s conversion.Scope) error {
	out.CacheTTL = in.CacheTTL
	out.URL = in.URL
	out.SecretFile = in.SecretFile
	return nil
}

// Convert_v1alpha1_AuthenticationWebhook_To_v1alpha3_AuthenticationWebhook is an autogenerated conversion function.
func Convert_v1alpha1_AuthenticationWebhook_To_v1alpha3_AuthenticationWebhook(in *AuthenticationWebhook, out *v1alpha3.AuthenticationWebhook, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthenticationWebhook_To_v1alpha3_AuthenticationWebhook(in, out, s)
}

func autoConvert_v1alpha3_AuthenticationWebhook_To_v1alpha1_AuthenticationWebhook(in *v1alpha3.AuthenticationWebhook, out *AuthenticationWebhook, s conversion.Scope) error {
	out.CacheTTL = in.CacheTTL
	out.URL = in.URL
	out.SecretFile = in.SecretFile
	return nil
}

// Convert_v1alpha3_AuthenticationWebhook_To_v1alpha1_AuthenticationWebhook is an autogenerated conversion function.
func Convert_v1alpha3_AuthenticationWebhook_To_v1alpha1_AuthenticationWebhook(in *v1alpha3.AuthenticationWebhook, out *AuthenticationWebhook, s conversion.Scope) error {
	return autoConvert_v1alpha3_AuthenticationWebhook_To_v1alpha1_AuthenticationWebhook(in, out, s)
}

func autoConvert_v1alpha1_AuthorizationWebhook_To_v1alpha3_AuthorizationWebhook(in *AuthorizationWebhook, out *v1alpha3.AuthorizationWebhook, s conversion.Scope) error {
	out.CacheAuthorizedTTL = in.CacheAuthorizedTTL
	out.CacheUnauthorizedTTL = in.CacheUnauthorizedTTL
	out.URL = in.URL
	out.SecretFile = in.SecretFile
	return nil
}

// Convert_v1alpha1_AuthorizationWebhook_To_v1alpha3_AuthorizationWebhook is an autogenerated conversion function.
func Convert_v1alpha1_AuthorizationWebhook_To_v1alpha3_AuthorizationWebhook(in *AuthorizationWebhook, out *v1alpha3.AuthorizationWebhook, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthorizationWebhook_To_v1alpha3_AuthorizationWebhook(in, out, s)
}

func autoConvert_v1alpha3_AuthorizationWebhook_To_v1alpha1_AuthorizationWebhook(in *v1alpha3.AuthorizationWebhook, out *AuthorizationWebhook, s conversion.Scope) error {
	out.CacheAuthorizedTTL = in.CacheAuthorizedTTL
	out.CacheUnauthorizedTTL = in.CacheUnauthorizedTTL
	out.URL = in.URL
	out.SecretFile = in.SecretFile
	return nil
}

// Convert_v1alpha3_AuthorizationWebhook_To_v1alpha1_AuthorizationWebhook is an autogenerated conversion function.
func Convert_v1alpha3_AuthorizationWebhook_To_v1alpha1_AuthorizationWebhook(in *v1alpha3.AuthorizationWebhook, out *AuthorizationWebhook, s conversion.Scope) error {
	return autoConvert_v1alpha3_AuthorizationWebhook_To_v1alpha1_AuthorizationWebhook(in, out, s)
}

func autoConvert_v1alpha1_ClusterSpec_To_v1alpha3_ClusterSpec(in *ClusterSpec, out *v1alpha3.ClusterSpec, s conversion.Scope) error {
	// WARNING: in.ObjectMeta requires manual conversion: does not exist in peer-type
	out.User = in.User
	out.DeprecatedSSHKeyPath = in.DeprecatedSSHKeyPath
	out.HTTPProxy = in.HTTPProxy
	out.Authentication = (*v1alpha3.AuthenticationWebhook)(unsafe.Pointer(in.Authentication))
	out.Authorization = (*v1alpha3.AuthorizationWebhook)(unsafe.Pointer(in.Authorization))
	if err := Convert_v1alpha1_OSConfig_To_v1alpha3_OSConfig(&in.OS, &out.OS, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ContainerRuntime_To_v1alpha3_ContainerRuntime(&in.CRI, &out.CRI, s); err != nil {
		return err
	}
	out.ImageRepository = in.ImageRepository
	if err := Convert_v1alpha1_APIServer_To_v1alpha3_APIServer(&in.APIServer, &out.APIServer, s); err != nil {
		return err
	}
	out.KubeletArguments = *(*[]v1alpha3.ServerArgument)(unsafe.Pointer(&in.KubeletArguments))
	out.Addons = *(*[]v1alpha3.Addon)(unsafe.Pointer(&in.Addons))
	out.CloudProvider = in.CloudProvider
	return nil
}

func autoConvert_v1alpha3_ClusterSpec_To_v1alpha1_ClusterSpec(in *v1alpha3.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	out.User = in.User
	out.DeprecatedSSHKeyPath = in.DeprecatedSSHKeyPath
	out.HTTPProxy = in.HTTPProxy
	out.Authentication = (*AuthenticationWebhook)(unsafe.Pointer(in.Authentication))
	out.Authorization = (*AuthorizationWebhook)(unsafe.Pointer(in.Authorization))
	if err := Convert_v1alpha3_OSConfig_To_v1alpha1_OSConfig(&in.OS, &out.OS, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_ContainerRuntime_To_v1alpha1_ContainerRuntime(&in.CRI, &out.CRI, s); err != nil {
		return err
	}
	out.ImageRepository = in.ImageRepository
	// WARNING: in.ControlPlaneEndpoint requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha3_APIServer_To_v1alpha1_APIServer(&in.APIServer, &out.APIServer, s); err != nil {
		return err
	}
	out.KubeletArguments = *(*[]ServerArgument)(unsafe.Pointer(&in.KubeletArguments))
	out.Addons = *(*[]Addon)(unsafe.Pointer(&in.Addons))
	out.CloudProvider = in.CloudProvider
	return nil
}

func autoConvert_v1alpha1_ContainerRuntime_To_v1alpha3_ContainerRuntime(in *ContainerRuntime, out *v1alpha3.ContainerRuntime, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Package = in.Package
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_ContainerRuntime_To_v1alpha3_ContainerRuntime is an autogenerated conversion function.
func Convert_v1alpha1_ContainerRuntime_To_v1alpha3_ContainerRuntime(in *ContainerRuntime, out *v1alpha3.ContainerRuntime, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContainerRuntime_To_v1alpha3_ContainerRuntime(in, out, s)
}

func autoConvert_v1alpha3_ContainerRuntime_To_v1alpha1_ContainerRuntime(in *v1alpha3.ContainerRuntime, out *ContainerRuntime, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Package = in.Package
	out.Version = in.Version
	return nil
}

// Convert_v1alpha3_ContainerRuntime_To_v1alpha1_ContainerRuntime is an autogenerated conversion function.
func Convert_v1alpha3_ContainerRuntime_To_v1alpha1_ContainerRuntime(in *v1alpha3.ContainerRuntime, out *ContainerRuntime, s conversion.Scope) error {
	return autoConvert_v1alpha3_ContainerRuntime_To_v1alpha1_ContainerRuntime(in, out, s)
}

func autoConvert_v1alpha1_EndPoint_To_v1alpha3_EndPoint(in *EndPoint, out *v1alpha3.EndPoint, s conversion.Scope) error {
	out.Address = in.Address
	out.Port = in.Port
	return nil
}

// Convert_v1alpha1_EndPoint_To_v1alpha3_EndPoint is an autogenerated conversion function.
func Convert_v1alpha1_EndPoint_To_v1alpha3_EndPoint(in *EndPoint, out *v1alpha3.EndPoint, s conversion.Scope) error {
	return autoConvert_v1alpha1_EndPoint_To_v1alpha3_EndPoint(in, out, s)
}

func autoConvert_v1alpha3_EndPoint_To_v1alpha1_EndPoint(in *v1alpha3.EndPoint, out *EndPoint, s conversion.Scope) error {
	out.Address = in.Address
	out.Port = in.Port
	return nil
}

// Convert_v1alpha3_EndPoint_To_v1alpha1_EndPoint is an autogenerated conversion function.
func Convert_v1alpha3_EndPoint_To_v1alpha1_EndPoint(in *v1alpha3.EndPoint, out *EndPoint, s conversion.Scope) error {
	return autoConvert_v1alpha3_EndPoint_To_v1alpha1_EndPoint(in, out, s)
}

func autoConvert_v1alpha1_FileSpec_To_v1alpha3_FileSpec(in *FileSpec, out *v1alpha3.FileSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_SourceSpec_To_v1alpha3_SourceSpec(&in.Source, &out.Source, s); err != nil {
		return err
	}
	out.Destination = in.Destination
	return nil
}

// Convert_v1alpha1_FileSpec_To_v1alpha3_FileSpec is an autogenerated conversion function.
func Convert_v1alpha1_FileSpec_To_v1alpha3_FileSpec(in *FileSpec, out *v1alpha3.FileSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_FileSpec_To_v1alpha3_FileSpec(in, out, s)
}

func autoConvert_v1alpha3_FileSpec_To_v1alpha1_FileSpec(in *v1alpha3.FileSpec, out *FileSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_SourceSpec_To_v1alpha1_SourceSpec(&in.Source, &out.Source, s); err != nil {
		return err
	}
	out.Destination = in.Destination
	return nil
}

// Convert_v1alpha3_FileSpec_To_v1alpha1_FileSpec is an autogenerated conversion function.
func Convert_v1alpha3_FileSpec_To_v1alpha1_FileSpec(in *v1alpha3.FileSpec, out *FileSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_FileSpec_To_v1alpha1_FileSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineSpec_To_v1alpha3_MachineSpec(in *MachineSpec, out *v1alpha3.MachineSpec, s conversion.Scope) error {
	// WARNING: in.ObjectMeta requires manual conversion: does not exist in peer-type
	// WARNING: in.Address requires manual conversion: does not exist in peer-type
	// WARNING: in.Port requires manual conversion: does not exist in peer-type
	// WARNING: in.PrivateAddress requires manual conversion: does not exist in peer-type
	// WARNING: in.PrivateInterface requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha1_EndPoint_To_v1alpha3_EndPoint(&in.Private, &out.Private, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_EndPoint_To_v1alpha3_EndPoint(&in.Public, &out.Public, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_MachineSpec_To_v1alpha1_MachineSpec(in *v1alpha3.MachineSpec, out *MachineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_EndPoint_To_v1alpha1_EndPoint(&in.Private, &out.Private, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_EndPoint_To_v1alpha1_EndPoint(&in.Public, &out.Public, s); err != nil {
		return err
	}
	// WARNING: in.ProviderID requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_OSConfig_To_v1alpha3_OSConfig(in *OSConfig, out *v1alpha3.OSConfig, s conversion.Scope) error {
	out.Files = *(*[]v1alpha3.FileSpec)(unsafe.Pointer(&in.Files))
	return nil
}

// Convert_v1alpha1_OSConfig_To_v1alpha3_OSConfig is an autogenerated conversion function.
func Convert_v1alpha1_OSConfig_To_v1alpha3_OSConfig(in *OSConfig, out *v1alpha3.OSConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_OSConfig_To_v1alpha3_OSConfig(in, out, s)
}

func autoConvert_v1alpha3_OSConfig_To_v1alpha1_OSConfig(in *v1alpha3.OSConfig, out *OSConfig, s conversion.Scope) error {
	out.Files = *(*[]FileSpec)(unsafe.Pointer(&in.Files))
	return nil
}

// Convert_v1alpha3_OSConfig_To_v1alpha1_OSConfig is an autogenerated conversion function.
func Convert_v1alpha3_OSConfig_To_v1alpha1_OSConfig(in *v1alpha3.OSConfig, out *OSConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_OSConfig_To_v1alpha1_OSConfig(in, out, s)
}

func autoConvert_v1alpha1_ServerArgument_To_v1alpha3_ServerArgument(in *ServerArgument, out *v1alpha3.ServerArgument, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_ServerArgument_To_v1alpha3_ServerArgument is an autogenerated conversion function.
func Convert_v1alpha1_ServerArgument_To_v1alpha3_ServerArgument(in *ServerArgument, out *v1alpha3.ServerArgument, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServerArgument_To_v1alpha3_ServerArgument(in, out, s)
}

func autoConvert_v1alpha3_ServerArgument_To_v1alpha1_ServerArgument(in *v1alpha3.ServerArgument, out *ServerArgument, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_v1alpha3_ServerArgument_To_v1alpha1_ServerArgument is an autogenerated conversion function.
func Convert_v1alpha3_ServerArgument_To_v1alpha1_ServerArgument(in *v1alpha3.ServerArgument, out *ServerArgument, s conversion.Scope) error {
	return autoConvert_v1alpha3_ServerArgument_To_v1alpha1_ServerArgument(in, out, s)
}

func autoConvert_v1alpha1_SourceSpec_To_v1alpha3_SourceSpec(in *SourceSpec, out *v1alpha3.SourceSpec, s conversion.Scope) error {
	out.ConfigMap = in.ConfigMap
	out.Key = in.Key
	return nil
}

// Convert_v1alpha1_SourceSpec_To_v1alpha3_SourceSpec is an autogenerated conversion function.
func Convert_v1alpha1_SourceSpec_To_v1alpha3_SourceSpec(in *SourceSpec, out *v1alpha3.SourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SourceSpec_To_v1alpha3_SourceSpec(in, out, s)
}

func autoConvert_v1alpha3_SourceSpec_To_v1alpha1_SourceSpec(in *v1alpha3.SourceSpec, out *SourceSpec, s conversion.Scope) error {
	out.ConfigMap = in.ConfigMap
	out.Key = in.Key
	return nil
}

// Convert_v1alpha3_SourceSpec_To_v1alpha1_SourceSpec is an autogenerated conversion function.
func Convert_v1alpha3_SourceSpec_To_v1alpha1_SourceSpec(in *v1alpha3.SourceSpec, out *SourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_SourceSpec_To_v1alpha1_SourceSpec(in, out, s)
}
