---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
  namespace: ${NAMESPACE}
  labels:
    cluster.x-k8s.io/provider: infrastructure-existinginfra
spec:
  clusterNetwork:
    services:
      cidrBlocks: [10.96.0.0/12]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: cluster.local
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraCluster
    name: "${CLUSTER_NAME}"
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraCluster
metadata:
  name: "${CLUSTER_NAME}"
  namespace: ${NAMESPACE}
  labels:
    cluster.x-k8s.io/provider: infrastructure-existinginfra
spec:
  user: "${WK_SSH_USER}"
  os:
    files:
    - source:
        configmap: repo
        key: kubernetes.repo
      destination: /etc/yum.repos.d/kubernetes.repo
    - source:
        configmap: repo
        key: docker-ce.repo
      destination: /etc/yum.repos.d/docker-ce.repo
    - source:
        configmap: repo
        key: cloud-google-com.gpg.b64
      destination: /tmp/cloud-google-com.gpg.b64
    - source:
        configmap: docker
        key: daemon.json
      destination: /etc/docker/daemon.json
  cri:
    kind: docker
    package: docker-ce
    version: 19.03.8
---
apiVersion: cluster.weave.works/v1alpha3
kind: MachineDeployment
metadata:
  name: "${CLUSTER_NAME}-md-0"
  namespace: ${NAMESPACE}
  labels:
    cluster.x-k8s.io/provider: infrastructure-existinginfra
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "${CLUSTER_NAME}"
      version: "${KUBERNETES_VERSION}"
      infrastructureRef:
        name: "${CLUSTER_NAME}-md-0"
        apiVersion: cluster.weave.works/v1alpha3
        kind: ExistingInfraMachine
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: "${CLUSTER_NAME}-md-0"
  namespace: ${NAMESPACE}
  labels:
    cluster.x-k8s.io/provider: infrastructure-existinginfra
spec:
  template:
    spec:
---
apiVersion: cluster.weave.works/v1alpha3
kind: MachineDeployment
metadata:
  name: "${CLUSTER_NAME}-md-1"
  namespace: ${NAMESPACE}
  labels:
    cluster.x-k8s.io/provider: infrastructure-existinginfra
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "${CLUSTER_NAME}"
      version: "${KUBERNETES_VERSION}"
      infrastructureRef:
        name: "${CLUSTER_NAME}-md-1"
        apiVersion: cluster.weave.works/v1alpha3
        kind: ExistingInfraMachine
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: "${CLUSTER_NAME}-md-1"
  namespace: ${NAMESPACE}
  labels:
    cluster.x-k8s.io/provider: infrastructure-existinginfra
spec:
  template:
    spec:
